name: Close Jira issue
on:
  issues:
    types:
      - closed

jobs:
  close-issue:
    name: Close Jira issue
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

      - name: Extract number from issue title
        id: extract_number
        run: |
          TITLE="${{ github.event.issue.title }}"
          NUMBER=$(echo "$TITLE" | grep -oP '(?<=\*)\d+$')
          echo "EXTRACTED_NUMBER=$NUMBER" >> $GITHUB_ENV

      - name: Transition Jira Issue to Done
        env:
          PROJECT: S12P11A408
        uses: atlassian/gajira-transition@v3
        with:
          issue: "${{ env.PROJECT }}-${{ env.EXTRACTED_NUMBER }}"
          transition: 완료

      - name: Log completed transition
        run: echo "Jira Issue ${{ needs.create-issue.outputs.jira_issue }} was transitioned to Done"
